version: '3'

volumes:
  dbdata:
    driver: local

services:
  ticket:
    build:
      context: .
      dockerfile: dev.Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8092:8080
    environment:
      - CHOKIDAR_USEPOLLING=true
      - npm_config_unsafe_perm=true
