// app
export const SET_INITIAL_STATE      = 'APP/SET_INITIAL_STATE'
export const SET_DRAWER             = 'APP/SET_DRAWER'
export const SET_LOADING            = 'APP/SET_LOADING'
export const SET_MINI_DRAWER        = 'APP/SET_MINI_DRAWER'
export const SET_SNACKBAR           = 'APP/SET_SNACKBAR'
// auth
export const SET_USER               = 'AUTH/SET_USER'
export const SET_PERMISSION         = 'AUTH/SET_PERMISSION'
export const SET_GROUPS             = 'AUTH/SET_GROUPS'
// config
export const SET_CONFIGS            = 'CONFIG/SET_CONFIGS'
export const SET_CONFIGS_LOADING    = 'CONFIG/SET_CONFIGS_LOADING'
export const SET_CONFIGS_PAGINATION = 'CONFIG/SET_CONFIGS_PAGINATION'
// ticket
export const SET_TICKETS            = 'CARD/SET_TICKETS'
export const SET_TICKETS_LOADING    = 'CARD/SET_TICKETS_LOADING'
export const SET_TICKETS_PAGINATION = 'CARD/SET_TICKETS_PAGINATION'
// ticket type
export const SET_TICKET_TYPES            = 'CARD/SET_TICKET_TYPES'
export const SET_TICKET_TYPE_DETAIL      = 'CARD/SET_TICKET_TYPE_DETAIL'
export const SET_TICKET_TYPES_LOADING    = 'CARD/SET_TICKET_TYPES_LOADING'
export const SET_TICKET_TYPES_PAGINATION = 'CARD/SET_TICKET_TYPES_PAGINATION'
// source
export const SET_SOURCES            = 'CARD/SET_SOURCES'
export const SET_SOURCE_DETAIL      = 'CARD/SET_SOURCE_DETAIL'
export const SET_SOURCES_LOADING    = 'CARD/SET_SOURCES_LOADING'
export const SET_SOURCES_PAGINATION = 'CARD/SET_SOURCES_PAGINATION'

// user
export const SET_USERS            = 'CARD/SET_USERS'
export const SET_USER_DETAIL      = 'CARD/SET_USER_DETAIL'
export const SET_USERS_LOADING    = 'CARD/SET_USERS_LOADING'
export const SET_USERS_PAGINATION = 'CARD/SET_USERS_PAGINATION'

// role
export const SET_ROLES            = 'CARD/SET_ROLES'
export const SET_ROLE_DETAIL      = 'CARD/SET_ROLE_DETAIL'
export const SET_ROLES_LOADING    = 'CARD/SET_ROLES_LOADING'
export const SET_ROLES_PAGINATION = 'CARD/SET_ROLES_PAGINATION'
export const SET_ALL_ROLES        = 'CARD/SET_ALL_ROLES'

// permission
export const SET_PERMISSIONS            = 'CARD/SET_PERMISSIONS'
export const SET_PERMISSION_DETAIL      = 'CARD/SET_PERMISSION_DETAIL'
export const SET_PERMISSIONS_LOADING    = 'CARD/SET_PERMISSIONS_LOADING'
export const SET_PERMISSIONS_PAGINATION = 'CARD/SET_PERMISSIONS_PAGINATION'
